server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 86400000

spring:
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]

app:
  admin:
    username: ${ADMIN_USERNAME}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    fullname: ${ADMIN_FULLNAME}
  google:
    clientId: ${GOOGLE_CLIENT_ID}